sudo: required
services:
  - docker

before_install:
  - docker build -t jameschua/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jameschua/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-kuno"
  env: "Dockerkuno-env"
  bucket_name: "elasticbeanstalk-us-west-1-313935353700"
  bucket_path: "docker-kuno"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
